"""added password field

Revision ID: 084325791aa9
Revises: 81741b538008
Create Date: 2022-07-22 20:44:06.209265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084325791aa9'
down_revision = '81741b538008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
