"""removed author col

Revision ID: ec5a97f24a2d
Revises: 54f0c5a85f5a
Create Date: 2022-07-29 11:56:00.795107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec5a97f24a2d'
down_revision = '54f0c5a85f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
